version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: jobsearch_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ia_job_search

  redis:
    image: redis:7-alpine
    container_name: jobsearch_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  mongo_data:
  redis_data:
